---



- name: Play 01 get info from router by using ios_facts
  hosts: usb1ab6secrtr1
  connection: local
  gather_facts: no

  vars:
    cli:
      username: stison
      password: colourfulHoney46$
      host: usb1ab6secrtr1
    # ansible_command_timeout: 1200
    # iosFileName: testfile01.txt


  tasks:
    - name: task 01 get info from router by using ios_facts & save it in var ios_facts_data
      ios_facts:
        provider: "{{ cli }}"
          # host: 172.16.11.11
          # port: 22
          # authorize: yes
          # auth_pass: cisco12345
          # username: tison
          # password: cisco12345
      register: ios_facts_data


    - name: task no. 2 display results of ios_facts
      debug:
        var: ios_facts_data  