---



- name: Play 01 get info from router by using ios_facts
  hosts: av6Routers
  connection: local
  gather_facts: no

  vars:
    cli:
      username: stison
      password: colourfulHoney46$
      host: "{{inventory_hostname}}"
    ansible_command_timeout: 1200
    iosFileName: testfile08.txt
  
  
  tasks:
  #   - name: Task 01 using ios_facts module to get info from router
  #     ios_facts:
  #       provider: "{{ cli }}"
  #     register: data


  #   - name: Task 02 display router info using debug module
  #     debug:
  #       var: data



    - name: Task 03 copy testfile08.txt from flash to 10.200.0.46
      ios_command:
        provider: "{{ cli }}"
        commands:
          - command: 'copy tftp://10.200.0.46/{{ iosFileName }} flash:'
            prompt:  
              - "{{ iosFileName }}"
              # - 'Address or name of remote host'
              # - 'Destination filename'
            answer:
              - "\r"
              # - '10.200.0.46'
              # - 'testfile01.txt'

    # - name: Task 05 copy IOS from av6 pt rtr to 10.200.0.46
    #   cli_command:        
    #     command: 'copy flash: tftp'
    #     check_all: True
    #     prompt:
    #       - 'Source filename'
    #       - 'Address or name of remote host'
    #       - 'Destination filename'

    #     answer: 
    #       - 'testfile.txt'
    #       - '10.200.0.46'
    #       - 'testfile.txt'
              
            #  prompt: '[]'
            #  prompt: '[]'
            #  prompt: '[]'
            #  answer: "XPedite5205-IOS-1-15.7.3.M1.bin"
            #  answer: "10.200.0.46"
            #  answer: "\r"
      #  ios_facts:
      #     provider:
      #        host: 172.16.11.11
      #        port: 22
      #        authorize: yes
      #        auth_pass: cisco12345
      #        username: tison
      #        password: cisco12345
       #register: ios_facts_data


#      - name: task no. 2 display
#        debug:
#           var: ios_facts_data    


# provider: "{{ cli }}"
#         commands:


   

#   tasks:
#      - name: Task no.03 Config Loopback Interface on r1 & r2
#        with_items: "{{ ospfBasicConfig }}"
#        ios_config:
#           provider: "{{provider}}"
#           lines:
#              - int "{{ item.int }}"
#              - ip add "{{ item.ip_addr }}"
#              - desc "{{ item.desc }}"




#      - name: Task no.04 Config OSPF on r1 & r2 with process ID 11
#        with_items: "{{ ospfConfigInfo }}"
#        ios_config:
#           provider: "{{provider}}"
#           lines:
#              - networks "{{ advNet00 }}" 0.0.0.0 area 0
#              - networks "{{ advNet01 }}" 0.0.0.0 area 0
#              - networks "{{ advNet02 }}" 0.0.0.0 area 0
#           parent:
#              - router ospf 11