---







- name: Play 01 verify conx & proper authen
  hosts: usb1ab6secrtr1
  connection: local
  gather_facts: no

  vars:
    cli:
      username: stison
      password: colourfulHoney46$
      host: "{{inventory_hostname}}"
    # ansible_command_timeout: 1200
    # iosFileName: testfile08.txt




  tasks:
    - name: Task 02 verify verify authen with ios_command module
      ios_command:
        provider: "{{ cli }}"
        commands: 'exit'
        timeout: 1800
      #ignore_errors: yes
      register: dataOut


    - name: output dataOut
      debug:
        var: dataOut