---


- name: Play 01 copy new ios on av6 flash and verify authenticity
  hosts: usb1ab6secrtr1
  connection: local
  gather_facts: no



  vars:
    cli:
      username: stison
      password: colourfulHoney46$
      host: "{{inventory_hostname}}"
    iosShortName: 15.7(3)M1
    iosFileName: XPedite5205-IOS-1-15.7.3.M1.bin
  


  tasks:    
    - name: upgrade ios to latest if needed after verifying current  ios version
      ios_command:
        provider: "{{ cli }}"
        commands:
          - command: 'copy tftp://10.200.18.3/{{ iosFileName }} flash:'
            prompt:  
              - "{{ iosFileName }}"
            answer:
              - "\r"
        timeout: 3200


    
    - name: verify signature of the ios
      ios_command:
        provider: "{{ cli }}"
        commands:
          - 'show software authenticity file flash:{{ iosFileName }}'
      register: sigData


    - name: display value of sigData
      debug:
        var: sigData.stdout_lines

# - name: SET BOOT SYSTEM FLASH
    #   ios_config:
    #     provider: "{{ cli }}" 
    #     lines:
    #       - 'no boot system flash:XPedite5205-IOS-1-15.6.2.T3.bin'
    #       - 'boot system flash:{{ iosFileName }}'
    #     after: 'do wr'

    # - name: REBOOT ROUTER
    #   ios_command:
    #     provider: "{{ cli }}"
    #     commands:
    #       - command: 'reload'
    #         prompt:
    #           - '[confirm]'
    #         answer:
    #           - "\r"

    # - name: WAIT FOR ROUTER TO RETURN
    #   wait_for:
    #     host: "{{inventory_hostname}}"
    #     port: 22
    #     delay: 120
    #   delegate_to: localhost

    # - name: GATHER ROUTER FACTS FOR VERIFICATION
    #   ios_facts:
    #     provider: "{{ cli }}"

    # - name: show the current ios version on router
    #   debug:
    #     var: ansible_net_version